name: Publish Documentation

on:
  push:
    branches: ["master"]
    paths:
      - config/**
      - docs/**
      - extras/generate.*

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# If a job is already running cancel it
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Generate Documentation through generate.sh
        run: |
         chmod +x ./extras/generate.sh
         ./extras/generate.sh
        shell: bash
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
